language: python
python:
- '3.4'
install: pip install -r requirements.txt
env:
- CONFIG_PATH=piewhole.config.TravisConfig
before_script:
- psql -c 'create database 'piewhole_test';' -U postgres
script:
- PYTHONPATH=. python3 tests/test_integration.py
- PYTHONPATH=. python3 tests/test_smoke.py
notifications:
  pushover:
    api_key:
      secure: EpfkFf7JTCyXTg1vsM6rkxUmkLz7wtpzehRbLFh5BZXBedZM+EWJQfOeQZbe/R4iXqKPlOexoBbswOdI86DtSczsGN4jrefgfGszzrX1qxgmaW81kOqURHlOz+CQyNt1pIQUF+HG3HP5rEoMSEAEnDS1N78ESuA5nDlWu+Zw0aUEAmzJpvjov6B2G1yMyLDeD3sinu9RWN1HfHRc28hSFrqrtFQndQqTyZk6lsqx7v+qjB+WNdvHHTeXq5HdH80q/8a9dj6XmgLAhsjbiAuPng5DnciGk2Oh4ATViVh3L+xs9rBF339e174PSYq6BhH/BMkkwyMTVQpyMAmY/rX0iF5R1OIRq/86GG5AExd8wLRZI8BtawWRIgcqpamf6U+aqQeDPygSfAzBLq8AmRlZYSpdsrK7s8IkD9AyHvUzsB0FQGRwtQJDMhdEz40TOVko22JrHaAFc9tZWlrK8TZAn9IKoLX++IrD7YMeSThsy6W6pswv84h+N+zklSAxQi/qDUfMp7Lcl6xE3ukBYtIoxieMBG+dE/R71SmLMjDc84WGSoyorYQ2semTKCZOqjOmoD+T+y6GeJcyncoTpD+ci/MwOeOBcM8dqaQhcvPA2DXT9Y4ILkH2rqvo9sDqWLlX08QrgiHwxSrVjE3nGnM8MriTr86vnbIKZPd3wlwQFnc=
    users:
      secure: Fmx03h6Fq6OBieuIccLidPFMdIiwLZc+oZjEDYyVNibsCenC6ln4nQe3siXZSronN7PdsU4bqTvwsxaD+CpgFcgu/BT/OY/lhMNGHyCRptS9aMTvxgkN3E4BSHBZXa7ywoDPZg5h0OFpMm0atD3xWXqOYPecLxhrbfmkLk6oIpYJv/G3YCD+Itj/3qWcA1yFNjxj029VpEmULiDQUgl1Th9F4yxb8lzz+BWxPvqfdWGweKDnEvdiEbheatAGso/2Pz480WgYmkXI81fhVyB/aKfFuQMdUQfsh/U/C9N5L6c2SuKgGigw0ooDGTDzEq+9kRJ356Bg9q7v19PCT7ZvNkOeuIZb/lEnawk+ngJlMGR1Brk/j4rzhWOvDqLtKgn4EMdQxFGzvKfgHQc2enMDFT0ykzQTWfvuQGv0vdFZK31w810P6juanGYoIUsaoajEzYSrkFDPZ6tZJLrj9mXuCq8lEL4FyY8ldYL3QW3XRgdaix14YMT2wnuvEPxI2Ma77USt3v+Qa0W8XyrXniS63Gu03BVWop2doXW4UT5l+lAdfAPJeZUVxtU0KlsGnlZhKUI3pmrzy7B91Cxd1mm3YOOrOF4KwmlCb00CWP84FR/ihf1nEd/aRaQg+C6GbvQsZ8bhds8k5IuiFuaadLlgjr5mYAo071sr63fNy0ajvwQ=
    template: "%{repository} (%{commit}) : %{message} %{foo} - Build details: %{build_url}"