language: python
python:
    - '3.4'
install: pip install -r requirements.txt
env:
    - CONFIG_PATH=piewhole.config.TravisConfig
before_script:
    - psql -c 'create database 'piewhole_test';' -U postgres
script:
    # basic tests
    - PYTHONPATH=. python3 tests/test_integration.py