"""empty message

Revision ID: 34936bf73e0
Revises: 41f8dfed461
Create Date: 2015-07-28 20:53:18.218984

"""

# revision identifiers, used by Alembic.
revision = '34936bf73e0'
down_revision = '41f8dfed461'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
