"""empty message

Revision ID: 3576b58c5b1
Revises: 4e77bda68a5
Create Date: 2015-08-08 11:02:59.996262

"""

# revision identifiers, used by Alembic.
revision = '3576b58c5b1'
down_revision = '4e77bda68a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    op.drop_constraint('Food_user_id_fkey', 'Food', type_='foreignkey')
    op.create_foreign_key(None, 'Food', 'Users', ['user_id'], ['id'])
    op.drop_constraint('Goals_user_id_fkey', 'Goals', type_='foreignkey')
    op.create_foreign_key(None, 'Goals', 'Users', ['user_id'], ['id'])
    op.create_unique_constraint(None, 'Users', ['id'])
    op.drop_constraint('Weight_user_id_fkey', 'Weight', type_='foreignkey')
    op.create_foreign_key(None, 'Weight', 'Users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Weight', type_='foreignkey')
    op.create_foreign_key('Weight_user_id_fkey', 'Weight', 'User', ['user_id'], ['id'])
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_constraint(None, 'Goals', type_='foreignkey')
    op.create_foreign_key('Goals_user_id_fkey', 'Goals', 'User', ['user_id'], ['id'])
    op.drop_constraint(None, 'Food', type_='foreignkey')
    op.create_foreign_key('Food_user_id_fkey', 'Food', 'User', ['user_id'], ['id'])
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"User_id_seq"\'::regclass)'), nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='User_pkey'),
    sa.UniqueConstraint('email', name='User_email_key'),
    sa.UniqueConstraint('id', name='User_id_key')
    )
    ### end Alembic commands ###
