"""empty message

Revision ID: 41f8dfed461
Revises: None
Create Date: 2015-07-28 20:51:40.591443

"""

# revision identifiers, used by Alembic.
revision = '41f8dfed461'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
