"""empty message

Revision ID: 4587c08afdf
Revises: 34936bf73e0
Create Date: 2015-07-29 19:43:42.029734

"""

# revision identifiers, used by Alembic.
revision = '4587c08afdf'
down_revision = '34936bf73e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
