"""empty message

Revision ID: 4e77bda68a5
Revises: 631ecd6b4
Create Date: 2015-07-30 12:43:38.200282

"""

# revision identifiers, used by Alembic.
revision = '4e77bda68a5'
down_revision = '631ecd6b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
