"""empty message

Revision ID: 5129f84ce10
Revises: 4587c08afdf
Create Date: 2015-07-29 21:53:34.907721

"""

# revision identifiers, used by Alembic.
revision = '5129f84ce10'
down_revision = '4587c08afdf'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Food', ['id'])
    op.create_unique_constraint(None, 'Goals', ['id'])
    op.create_unique_constraint(None, 'Ranks', ['id'])
    op.create_unique_constraint(None, 'User', ['id'])
    op.create_unique_constraint(None, 'Weight', ['id'])
    op.drop_column('Weight', 'weight_delta')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Weight', sa.Column('weight_delta', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Weight', type_='unique')
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'Ranks', type_='unique')
    op.drop_constraint(None, 'Goals', type_='unique')
    op.drop_constraint(None, 'Food', type_='unique')
    ### end Alembic commands ###
